[package]
name = "shared-types"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-ec2 = "1.62.0"
aws-sdk-elasticloadbalancing = "1.37.0"
aws-sdk-elasticloadbalancingv2 = "1.39.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
