[package]
name = "subnet-checks"
version = "0.1.0"
edition = "2021"

[dependencies]
extism-pdk = "1.2.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"

[lib]
crate-type = ["cdylib"]
